x-tester-base: &tester_base
  image: python:3.11-slim
  depends_on:
    orchestrator:
      condition: service_started          
  working_dir: /opt
  environment:
    - ARTIFACTS_DIR=/opt/logs_testing
    - TEST_INPUT_DIR=/opt/input_pdfs 
    - ORCH_BASE=http://orchestrator:5001   
    - DOCLING_BASE=http://docling:5004   
    - LABEL_STUDIO_LEGACY_TOKEN=${LABEL_STUDIO_LEGACY_TOKEN}
    - PYTHONPATH=/opt/tests 
  volumes:
    - ./tests:/opt/tests:ro
    - ./pytest.ini:/opt/pytest.ini:ro
    - ./requirements-test.txt:/opt/requirements-test.txt:ro
    - ./logs_testing:/opt/logs_testing
    - ./tests/e2e/data/input_pdfs:/opt/input_pdfs:ro
    - ./data/pdfs:/pdfs
    - ./data/htmls:/htmls
    - ./data/projects:/projects

services:
  # ---- Smoke suite ----
  tester-smoke:
    <<: *tester_base
    profiles: ["smoke"]
    entrypoint: >
      sh -lc '
        set -euo pipefail;
        RUN_ID=$$(date -u +%Y%m%dT%H%M%SZ);
        mkdir -p "$${ARTIFACTS_DIR}/smoke/$${RUN_ID}";
        LOG="$${ARTIFACTS_DIR}/smoke/$${RUN_ID}/pytest.log";
        JUNIT="$${ARTIFACTS_DIR}/smoke/$${RUN_ID}/junit.xml";
        apt-get update &&
        apt-get install -y --no-install-recommends curl ca-certificates &&
        rm -rf /var/lib/apt/lists/* &&
        python -m pip install --upgrade pip &&
        pip install -r /opt/requirements-test.txt &&
        for i in $$(seq 1 60); do curl -fsS http://orchestrator:5001/health && break || sleep 2; done;
        echo "[INFO] Running SMOKE tests (RUN_ID=$$RUN_ID)";
        pytest -c /opt/pytest.ini /opt/tests/smoke -vv -s \
          --junitxml="$$JUNIT" 2>&1 | tee "$$LOG"
      '

  # ---- E2E suite ----
  tester-e2e:
    <<: *tester_base
    profiles: ["e2e"]
    entrypoint: >
      sh -lc '
        set -euo pipefail;
        RUN_ID=$$(date -u +%Y%m%dT%H%M%SZ);
        mkdir -p "$${ARTIFACTS_DIR}/e2e/$${RUN_ID}";
        LOG="$${ARTIFACTS_DIR}/e2e/$${RUN_ID}/pytest.log";
        JUNIT="$${ARTIFACTS_DIR}/e2e/$${RUN_ID}/junit.xml";
        apt-get update &&
        apt-get install -y --no-install-recommends curl ca-certificates &&
        rm -rf /var/lib/apt/lists/* &&
        python -m pip install --upgrade pip &&
        pip install -r /opt/requirements-test.txt &&
        for i in $$(seq 1 60); do curl -fsS http://orchestrator:5001/health && break || sleep 2; done;
        echo "[INFO] Running E2E tests (RUN_ID=$$RUN_ID)";
        pytest -c /opt/pytest.ini /opt/tests/e2e -vv -s \
          --junitxml="$$JUNIT" 2>&1 | tee "$$LOG"
      '