x-tester-base: &tester_base
  image: python:3.11-slim
  depends_on:
    orchestrator:
      condition: service_started
  working_dir: /opt
  environment:
    - BASE_URL=http://orchestrator:5001
  volumes:
    - ./tests:/opt/tests:ro
    - ./pytest.ini:/opt/pytest.ini:ro
    - ./requirements-test.txt:/opt/requirements-test.txt:ro

services:
  # ---- Smoke suite ----
  tester-smoke:
    <<: *tester_base
    profiles: ["smoke"]
    entrypoint: >
      sh -lc "
        set -euo pipefail;
        apt-get update &&
        apt-get install -y --no-install-recommends curl ca-certificates &&
        rm -rf /var/lib/apt/lists/* &&
        python -m pip install --upgrade pip &&
        pip install -r /opt/requirements-test.txt &&
        for i in $(seq 1 60); do curl -fsS http://orchestrator:5001/health && break || sleep 2; done;
        echo '[INFO] Running SMOKE tests';
        pytest -c /opt/pytest.ini /opt/tests/smoke -q
      "

  # ---- E2E suite ----
  tester-e2e:
    <<: *tester_base
    profiles: ["e2e"]
    entrypoint: >
      sh -lc "
        set -euo pipefail;
        apt-get update &&
        apt-get install -y --no-install-recommends curl ca-certificates &&
        rm -rf /var/lib/apt/lists/* &&
        python -m pip install --upgrade pip &&
        pip install -r /opt/requirements-test.txt &&
        for i in $(seq 1 60); do curl -fsS http://orchestrator:5001/health && break || sleep 2; done;
        echo '[INFO] Running E2E tests';
        pytest -c /opt/pytest.ini /opt/tests/e2e -q
      "