"""Add missing task_metrics, performance, labels to Evaluation table

Revision ID: 073047bfcb9b
Revises: b4186650c55b
Create Date: 2026-08-01 05:39:19.209801

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "073047bfcb9b"
down_revision: Union[str, Sequence[str], None] = "b4186650c55b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evaluations",
        sa.Column("task_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "evaluations",
        sa.Column("performance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "evaluations", sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluations", "labels")
    op.drop_column("evaluations", "performance")
    op.drop_column("evaluations", "task_metrics")
    # ### end Alembic commands ###
