"""initial schema

Revision ID: 1b794710f826
Revises:
Create Date: 2026-05-14 11:59:14.064281

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b794710f826"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("questions_and_labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("label_studio_id", sa.Integer(), nullable=True),
        sa.Column("ollama_model", sa.Text(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("llm_timeout_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project", sa.Text(), nullable=False),
        sa.Column("groundtruth_project", sa.Text(), nullable=False),
        sa.Column("comparison_project", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("run_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("metrics_micro", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metrics_per_label", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("performance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project"],
            ["projects.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("pdf_path", sa.Text(), nullable=True),
        sa.Column("html_path", sa.Text(), nullable=True),
        sa.Column("pdf_key", sa.Text(), nullable=True),
        sa.Column("html_key", sa.Text(), nullable=True),
        sa.Column("pdf_hash", sa.Text(), nullable=True),
        sa.Column("html_hash", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project"],
            ["projects.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project", "filename", name="uq_files_project_filename"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("files")
    op.drop_table("evaluations")
    op.drop_table("projects")
    # ### end Alembic commands ###
