"""Change groundtruth column in Project from boolean to 'none', 'internal', 'external' to allow for internal groundtruth sets

Revision ID: 21fc2217176d
Revises: 073047bfcb9b
Create Date: 2026-08-10 14:54:29.492082

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21fc2217176d"
down_revision: Union[str, Sequence[str], None] = "073047bfcb9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("groundtruth", sa.Text(), nullable=False))
    op.drop_index(
        op.f("uq_groundtruth_labels_documents"),
        table_name="projects",
        postgresql_where="(is_groundtruth IS TRUE)",
    )
    op.create_index(
        "uq_external_groundtruth_labels_documents",
        "projects",
        ["labels_hash", "document_set_hash"],
        unique=True,
        postgresql_where=sa.text("groundtruth = 'external'"),
    )
    op.drop_column("projects", "is_groundtruth")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("is_groundtruth", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.drop_index(
        "uq_external_groundtruth_labels_documents",
        table_name="projects",
        postgresql_where=sa.text("groundtruth = 'external'"),
    )
    op.create_index(
        op.f("uq_groundtruth_labels_documents"),
        "projects",
        ["labels_hash", "document_set_hash"],
        unique=True,
        postgresql_where="(is_groundtruth IS TRUE)",
    )
    op.drop_column("projects", "groundtruth")
    # ### end Alembic commands ###
