"""Rename run_id to job_id for consistency

Revision ID: 46b76193db91
Revises: cae661096175
Create Date: 2026-06-13 08:54:07.797210

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46b76193db91"
down_revision: Union[str, Sequence[str], None] = "cae661096175"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluations", sa.Column("job_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("evaluations_prelabelling_run_id_fkey"), "evaluations", type_="foreignkey"
    )
    op.create_foreign_key(None, "evaluations", "prelabelling_runs", ["job_id"], ["id"])
    op.drop_column("evaluations", "prelabelling_run_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evaluations",
        sa.Column("prelabelling_run_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "evaluations", type_="foreignkey")
    op.create_foreign_key(
        op.f("evaluations_prelabelling_run_id_fkey"),
        "evaluations",
        "prelabelling_runs",
        ["prelabelling_run_id"],
        ["id"],
    )
    op.drop_column("evaluations", "job_id")
    # ### end Alembic commands ###
