"""Add information about label studio upload in project table

Revision ID: 692cc3b69640
Revises: 9bfa86a4eb72
Create Date: 2026-06-07 08:54:35.444233

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "692cc3b69640"
down_revision: Union[str, Sequence[str], None] = "9bfa86a4eb72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("ls_tasks_uploaded", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "ls_tasks_uploaded")
    # ### end Alembic commands ###
