"""Add number of files included into evaluation to Evaluation table

Revision ID: 6b8d1a84ae38
Revises: ae49f76f801a
Create Date: 2026-06-28 06:27:12.677482

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b8d1a84ae38"
down_revision: Union[str, Sequence[str], None] = "ae49f76f801a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluations", sa.Column("filenames_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluations", "filenames_count")
    # ### end Alembic commands ###
