"""Add questions_hash and document_set_hash, add unique constraint to avoid multiple projects with gt=true and same documents + labels, add unique constraint to avoid multiple evaluations for same combination of gt project and comparison_prelabelling_run_id

Revision ID: 6e31bbabcaa9
Revises: 72fe2c5ab0bb
Create Date: 2026-07-31 15:09:23.050786

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e31bbabcaa9"
down_revision: Union[str, Sequence[str], None] = "72fe2c5ab0bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_evaluations_gt_project_run",
        "evaluations",
        ["groundtruth_project", "comparison_prelabelling_run_id"],
    )
    op.add_column("prelabelling_runs", sa.Column("questions_hash", sa.Text(), nullable=True))
    op.add_column("prelabelling_runs", sa.Column("system_prompt_hash", sa.Text(), nullable=True))
    op.add_column("projects", sa.Column("questions_hash", sa.Text(), nullable=True))
    op.add_column("projects", sa.Column("document_set_hash", sa.Text(), nullable=True))
    op.create_index(
        "uq_groundtruth_labels_documents",
        "projects",
        ["labels_hash", "document_set_hash"],
        unique=True,
        postgresql_where=sa.text("is_groundtruth IS TRUE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_groundtruth_labels_documents",
        table_name="projects",
        postgresql_where=sa.text("is_groundtruth IS TRUE"),
    )
    op.drop_column("projects", "document_set_hash")
    op.drop_column("projects", "questions_hash")
    op.drop_column("prelabelling_runs", "system_prompt_hash")
    op.drop_column("prelabelling_runs", "questions_hash")
    op.drop_constraint("uq_evaluations_gt_project_run", "evaluations", type_="unique")
    # ### end Alembic commands ###
