"""Add models table for documenting digest etc., change PrelabellingRun.ollama_model to PrelabellingRun.model_id as ForeignKey to improve traceability

Revision ID: 72fe2c5ab0bb
Revises: 6b8d1a84ae38
Create Date: 2026-07-26 06:19:29.181964

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72fe2c5ab0bb"
down_revision: Union[str, Sequence[str], None] = "6b8d1a84ae38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.Text(), nullable=False),
        sa.Column("digest", sa.Text(), nullable=False),
        sa.Column("archived_name", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("family", sa.Text(), nullable=True),
        sa.Column("parameter_size", sa.Text(), nullable=True),
        sa.Column("quantization_level", sa.Text(), nullable=True),
        sa.Column("ollama_version", sa.Text(), nullable=True),
        sa.Column("pulled_via", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "last_confirmed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("archived_name"),
        sa.UniqueConstraint("digest", name="uq_models_digest"),
    )
    op.add_column("prelabelling_runs", sa.Column("model_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "prelabelling_runs", "models", ["model_id"], ["id"])
    op.drop_column("prelabelling_runs", "ollama_model")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prelabelling_runs",
        sa.Column("ollama_model", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "prelabelling_runs", type_="foreignkey")
    op.drop_column("prelabelling_runs", "model_id")
    op.drop_table("models")
    # ### end Alembic commands ###
