"""add constraint for prelabelling_runs.status and remove unused prelabellung_runs.labelstudio_id

Revision ID: 74389598266b
Revises: ba5d1ff1f836
Create Date: 2026-09-29 12:59:37.703422

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74389598266b"
down_revision: Union[str, Sequence[str], None] = "ba5d1ff1f836"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prelabelling_runs", "label_studio_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prelabelling_runs",
        sa.Column("label_studio_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
