"""add label_studio_id and is_groundtruth to projects

Revision ID: 9bfa86a4eb72
Revises: d4d4dd501f95
Create Date: 2026-06-06 06:50:48.867110

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bfa86a4eb72"
down_revision: Union[str, Sequence[str], None] = "d4d4dd501f95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("label_studio_id", sa.Integer(), nullable=True))
    op.add_column("projects", sa.Column("is_groundtruth", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "is_groundtruth")
    op.drop_column("projects", "label_studio_id")
    # ### end Alembic commands ###
