"""Add questions and labels to prelabelling run table again, preferring better traceability over no duplications

Revision ID: a6f8b5a1905c
Revises: 46b76193db91
Create Date: 2026-06-13 10:05:09.650955

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a6f8b5a1905c"
down_revision: Union[str, Sequence[str], None] = "46b76193db91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prelabelling_runs",
        sa.Column("questions_and_labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prelabelling_runs", "questions_and_labels")
    # ### end Alembic commands ###
