"""Add hashes for labels to Project table and additionally in PrelabellingRun table (here only for traceability)

Revision ID: ae49f76f801a
Revises: cda566a9310b
Create Date: 2026-06-27 11:55:29.329362

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae49f76f801a"
down_revision: Union[str, Sequence[str], None] = "cda566a9310b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prelabelling_runs", sa.Column("labels_hash", sa.Text(), nullable=True))
    op.add_column("projects", sa.Column("labels_hash", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "labels_hash")
    op.drop_column("prelabelling_runs", "labels_hash")
    # ### end Alembic commands ###
