"""Add UniqueConstraint for project to PrelabellingRun table to enforce the restriction on db level as well

Revision ID: ba5d1ff1f836
Revises: f4726497e94f
Create Date: 2026-09-05 10:48:11.568354

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba5d1ff1f836"
down_revision: Union[str, Sequence[str], None] = "f4726497e94f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_prelabelling_runs_project", "prelabelling_runs", ["project"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_prelabelling_runs_project", "prelabelling_runs", type_="unique")
    # ### end Alembic commands ###
