"""add cancel_requested column to PrelabellingRun table

Revision ID: ca90a1484ad3
Revises: e3c42bbff3f5
Create Date: 2026-10-02 07:43:52.871405

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca90a1484ad3"
down_revision: Union[str, Sequence[str], None] = "e3c42bbff3f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prelabelling_runs",
        sa.Column("cancel_requested", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prelabelling_runs", "cancel_requested")
    # ### end Alembic commands ###
