"""Move questions and labels to project table (as we will only allow for one qal set per project) , remove duplicates in prelabelling run table

Revision ID: cae661096175
Revises: 692cc3b69640
Create Date: 2026-06-13 06:23:55.042180

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cae661096175"
down_revision: Union[str, Sequence[str], None] = "692cc3b69640"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prelabelling_runs", sa.Column("error", sa.Text(), nullable=True))
    op.drop_column("prelabelling_runs", "questions_and_labels")
    op.drop_column("prelabelling_runs", "label_studio_project_name")
    op.add_column(
        "projects",
        sa.Column("questions_and_labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "questions_and_labels")
    op.add_column(
        "prelabelling_runs",
        sa.Column("label_studio_project_name", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "prelabelling_runs",
        sa.Column(
            "questions_and_labels",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("prelabelling_runs", "error")
    # ### end Alembic commands ###
