"""Add TaskPrelabellingMeta for performance data and prelabelling results (to save them outside label studio making label studio only a HITL tool) and add TaskGroundtruthAnnotation to later backup ground truth outside label studio as well

Revision ID: cda566a9310b
Revises: a6f8b5a1905c
Create Date: 2026-06-20 07:33:20.811829

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cda566a9310b"
down_revision: Union[str, Sequence[str], None] = "a6f8b5a1905c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_groundtruth_annotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project", sa.Text(), nullable=False),
        sa.Column("label_studio_task_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("annotations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project"],
            ["projects.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project", "label_studio_task_id", name="uq_task_groundtruth_annotation_project_task"
        ),
    )
    op.create_table(
        "task_prelabelling_metas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prelabelling_run_id", sa.Integer(), nullable=False),
        sa.Column("label_studio_task_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("predictions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_llm_answers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dom_match_diagnostics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dom_match_by_label", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("task_ms_total", sa.Float(), nullable=True),
        sa.Column("task_ms_llm_total", sa.Float(), nullable=True),
        sa.Column("task_ms_dom_extract", sa.Float(), nullable=True),
        sa.Column("task_ms_dom_match", sa.Float(), nullable=True),
        sa.Column("n_llm_calls", sa.Integer(), nullable=True),
        sa.Column("n_timeouts", sa.Integer(), nullable=True),
        sa.Column("avg_llm_call_ms", sa.Float(), nullable=True),
        sa.Column("median_llm_call_ms", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["prelabelling_run_id"],
            ["prelabelling_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "prelabelling_run_id", "label_studio_task_id", name="uq_task_prelabelling_meta_run_task"
        ),
    )
    op.add_column(
        "evaluations", sa.Column("comparison_prelabelling_run_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(op.f("evaluations_job_id_fkey"), "evaluations", type_="foreignkey")
    op.drop_constraint(op.f("evaluations_project_fkey"), "evaluations", type_="foreignkey")
    op.create_foreign_key(None, "evaluations", "projects", ["groundtruth_project"], ["name"])
    op.create_foreign_key(
        None, "evaluations", "prelabelling_runs", ["comparison_prelabelling_run_id"], ["id"]
    )
    op.drop_column("evaluations", "performance")
    op.drop_column("evaluations", "job_id")
    op.drop_column("evaluations", "project")
    op.drop_column("evaluations", "comparison_project")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evaluations",
        sa.Column("comparison_project", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "evaluations", sa.Column("project", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "evaluations", sa.Column("job_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "evaluations",
        sa.Column(
            "performance",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "evaluations", type_="foreignkey")
    op.drop_constraint(None, "evaluations", type_="foreignkey")
    op.create_foreign_key(
        op.f("evaluations_project_fkey"), "evaluations", "projects", ["project"], ["name"]
    )
    op.create_foreign_key(
        op.f("evaluations_job_id_fkey"), "evaluations", "prelabelling_runs", ["job_id"], ["id"]
    )
    op.drop_column("evaluations", "comparison_prelabelling_run_id")
    op.drop_table("task_prelabelling_metas")
    op.drop_table("task_groundtruth_annotations")
    # ### end Alembic commands ###
