"""add PrelabellingRun table and remove its columns from previous tables

Revision ID: d4d4dd501f95
Revises: 8dd9f23f1cf0
Create Date: 2026-05-31 10:10:15.054205

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4d4dd501f95"
down_revision: Union[str, Sequence[str], None] = "8dd9f23f1cf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prelabelling_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project", sa.Text(), nullable=False),
        sa.Column("label_studio_project_name", sa.Text(), nullable=False),
        sa.Column("label_studio_id", sa.Integer(), nullable=True),
        sa.Column("questions_and_labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ollama_model", sa.Text(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("llm_timeout_seconds", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project"],
            ["projects.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("evaluations", sa.Column("prelabelling_run_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "evaluations", "prelabelling_runs", ["prelabelling_run_id"], ["id"])
    op.drop_column("evaluations", "system_prompt")
    op.drop_column("evaluations", "model")
    op.add_column("files", sa.Column("error", sa.Text(), nullable=True))
    op.drop_column("files", "pdf_path")
    op.drop_column("files", "html_path")
    op.drop_column("projects", "label_studio_id")
    op.drop_column("projects", "llm_timeout_seconds")
    op.drop_column("projects", "questions_and_labels")
    op.drop_column("projects", "ollama_model")
    op.drop_column("projects", "system_prompt")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("system_prompt", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "projects", sa.Column("ollama_model", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "projects",
        sa.Column(
            "questions_and_labels",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "projects",
        sa.Column("llm_timeout_seconds", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects", sa.Column("label_studio_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column("files", sa.Column("html_path", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("files", sa.Column("pdf_path", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column("files", "error")
    op.add_column("evaluations", sa.Column("model", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "evaluations", sa.Column("system_prompt", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "evaluations", type_="foreignkey")
    op.drop_column("evaluations", "prelabelling_run_id")
    op.drop_table("prelabelling_runs")
    # ### end Alembic commands ###
