"""Add table PrelabellingRunTask to later replace TaskPrelabellingMeta, PrelabellingRunTask will include results and status information

Revision ID: e3c42bbff3f5
Revises: 74389598266b
Create Date: 2026-09-30 11:50:55.747879

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e3c42bbff3f5"
down_revision: Union[str, Sequence[str], None] = "74389598266b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prelabelling_run_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prelabelling_run_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("label_studio_task_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("predictions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_llm_answers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dom_match_diagnostics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dom_match_by_label", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("task_ms_total", sa.Float(), nullable=True),
        sa.Column("task_ms_llm_total", sa.Float(), nullable=True),
        sa.Column("task_ms_dom_extract", sa.Float(), nullable=True),
        sa.Column("task_ms_dom_match", sa.Float(), nullable=True),
        sa.Column("n_llm_calls", sa.Integer(), nullable=True),
        sa.Column("n_timeouts", sa.Integer(), nullable=True),
        sa.Column("avg_llm_call_ms", sa.Float(), nullable=True),
        sa.Column("median_llm_call_ms", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'success', 'failed')",
            name="ck_prelabelling_run_tasks_status_values",
        ),
        sa.ForeignKeyConstraint(
            ["prelabelling_run_id"],
            ["prelabelling_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "prelabelling_run_id", "filename", name="uq_prelabelling_run_tasks_run_filename"
        ),
        sa.UniqueConstraint(
            "prelabelling_run_id", "label_studio_task_id", name="uq_prelabelling_run_tasks_run_task"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prelabelling_run_tasks")
    # ### end Alembic commands ###
