"""remove task_prelabelling_metas table (replaced by prelabelling_run_tasks table)

Revision ID: e9f70d30f799
Revises: ca90a1484ad3
Create Date: 2026-10-03 13:07:58.452633

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e9f70d30f799"
down_revision: Union[str, Sequence[str], None] = "ca90a1484ad3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_prelabelling_metas")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_prelabelling_metas",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("prelabelling_run_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("label_studio_task_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("filename", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "predictions",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "raw_llm_answers",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "dom_match_diagnostics",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "dom_match_by_label",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "task_ms_total", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "task_ms_llm_total",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "task_ms_dom_extract",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "task_ms_dom_match",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("n_llm_calls", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("n_timeouts", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "avg_llm_call_ms", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "median_llm_call_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["prelabelling_run_id"],
            ["prelabelling_runs.id"],
            name=op.f("task_prelabelling_metas_prelabelling_run_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("task_prelabelling_metas_pkey")),
        sa.UniqueConstraint(
            "prelabelling_run_id",
            "label_studio_task_id",
            name=op.f("uq_task_prelabelling_meta_run_task"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
