"""Update conversion_jobs table status with constraint on 'pending', 'converting', 'done', 'failed', 'cancelled' thereby also adding new 'cancelled' status

Revision ID: ed59d349a6d7
Revises: 21fc2217176d
Create Date: 2026-08-22 08:33:03.885860

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ed59d349a6d7"
down_revision: Union[str, Sequence[str], None] = "21fc2217176d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
