"""Remove questions_and_labels, labels_hash and questions_hash from PrelabellingRun table (redundant to Project table due to current workflow setting them with project creation for all future prelabelling runs)

Revision ID: f4726497e94f
Revises: ed59d349a6d7
Create Date: 2026-09-05 08:08:52.924264

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f4726497e94f"
down_revision: Union[str, Sequence[str], None] = "ed59d349a6d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prelabelling_runs", "labels_hash")
    op.drop_column("prelabelling_runs", "questions_and_labels")
    op.drop_column("prelabelling_runs", "questions_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prelabelling_runs",
        sa.Column("questions_hash", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prelabelling_runs",
        sa.Column(
            "questions_and_labels",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "prelabelling_runs", sa.Column("labels_hash", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
