#!/bin/sh
# fhir_seed/load_bundles.sh
#
# Loads the FHIR bundles baked into this image at /bundles (generated by
# Synthea at build time, see docker/fhir_seed/Dockerfile) into the fhir
# server's transaction endpoint.
#
# Synthea writes hospitalInformation*.json and practitionerInformation*.json
# alongside the per-patient bundles; patient bundles reference those
# Organization/Practitioner resources, so they must be loaded first or the
# reference resolution inside the transaction will fail.

set -eu

FHIR_BASE="http://${FHIR_CONTAINER_NAME:-fhir}:8080/fhir"
BUNDLE_DIR="/bundles"

echo "fhir_seed: waiting for ${FHIR_BASE}/metadata to respond..."
until curl -sf "${FHIR_BASE}/metadata" > /dev/null; do
  sleep 2
done

post_bundle() {
  bundle="$1"
  http_status=$(curl -s -o /tmp/fhir_seed_response.json -w "%{http_code}" \
    -X POST "${FHIR_BASE}" \
    -H "Content-Type: application/fhir+json" \
    --data-binary "@${bundle}")

  if [ "$http_status" -ge 200 ] && [ "$http_status" -lt 300 ]; then
    echo "fhir_seed: OK ($http_status) - $(basename "$bundle")"
    return 0
  else
    echo "fhir_seed: FAILED ($http_status) - $(basename "$bundle")"
    cat /tmp/fhir_seed_response.json
    return 1
  fi
}

if [ ! -d "$BUNDLE_DIR" ]; then
  echo "fhir_seed: ${BUNDLE_DIR} not found in image — build step may have failed."
  exit 1
fi

count=0

for bundle in "$BUNDLE_DIR"/hospitalInformation*.json "$BUNDLE_DIR"/practitionerInformation*.json; do
  [ -e "$bundle" ] || continue
  echo "fhir_seed: loading reference bundle $(basename "$bundle")"
  post_bundle "$bundle" && count=$((count + 1))
done

for bundle in "$BUNDLE_DIR"/*.json; do
  [ -e "$bundle" ] || continue
  case "$(basename "$bundle")" in
    hospitalInformation*.json|practitionerInformation*.json) continue ;;
  esac
  echo "fhir_seed: loading patient bundle $(basename "$bundle")"
  post_bundle "$bundle" && count=$((count + 1))
done

echo "fhir_seed: done, loaded ${count} bundle(s)."